name: speedcore

services:
  speed_db:
    image: postgres:17
    container_name: speed_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - speed_db:/var/lib/postgresql/data
    networks:
      - speednet
  speed_persistence:
    container_name: speed_persistence
    build: ./services/persistence
    environment:
      SPEED_DB_DSN: ${SPEED_DB_DSN}
    networks:
      - speednet

volumes:
  speed_db:
    name: speed_db

networks:
  speednet:
    name: speednet
    driver: bridge