services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yaml
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Dashboard
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Provide Docker socke
      - ./traefik/acme.json:/etc/traefik/acme.json # Provide certificate file
    environment:
      - CLOUDFLARE_DNS_API_TOKEN
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-router.rule=Host(`api.speedsolve.xyz`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.dashboard-router.service=api@internal"
      - "traefik.http.routers.dashboard-router.entrypoints=websecure"
      - "traefik.http.routers.dashboard-router.tls=true"
      - "traefik.http.routers.dashboard-router.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      - "traefik.http.routers.dashboard-router.middlewares=auth"
  profile:
    build: ./services/profile/
    container_name: profile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.profile-router.rule=Host(`api.speedsolve.xyz`) && PathPrefix(`/profile`)"
      - "traefik.http.routers.profile-router.entrypoints=websecure"
      - "traefik.http.routers.profile-router.tls=true"
      - "traefik.http.routers.profile-router.tls.certresolver=letsencrypt"
      - "traefik.http.services.profile-service.loadbalancer.server.port=8000"
      - "traefik.http.services.profile-service.loadbalancer.healthcheck.path=/profile/health"
      - "traefik.http.services.profile-service.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.profile-service.loadbalancer.healthcheck.timeout=3s"
  competition:
    build: ./services/competition/
    container_name: competition
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.competition-router.rule=Host(`api.speedsolve.xyz`) && PathPrefix(`/comp`)"
      - "traefik.http.routers.competition-router.entrypoints=websecure"
      - "traefik.http.routers.competition-router.tls=true"
      - "traefik.http.routers.competition-router.tls.certresolver=letsencrypt"
      - "traefik.http.services.competition-service.loadbalancer.server.port=8000"
      - "traefik.http.services.competition-service.loadbalancer.healthcheck.path=/comp/health"
      - "traefik.http.services.competition-service.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.competition-service.loadbalancer.healthcheck.timeout=3s"

networks:
  default:
    driver: bridge

