name: speedsolve-xyz

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - --configFile=/etc/traefik/traefik.yaml
    ports:
      - "80:80"     # HTTP
      - "8080:8080" # Dashboard
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Provide Docker socke
    labels:
      - "traefik.enable=true"
  health:
    build: ./services/health/
    container_name: health
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.health_router.rule=PathPrefix(`/health`)"
      - "traefik.http.routers.health_router.entrypoints=web"
      - "traefik.http.services.health.loadbalancer.server.port=80"


networks:
  default:
    driver: bridge

